$(function() {
    var windowWidth = window.outerWidth;
    for(var i = 1 ; i<=20 ; i++ ){
        $(".q-" + i).removeClass("show").css("display","none");
    }
    if(windowWidth >= 320 && windowWidth < 375){
        $(".second-hex-text").removeClass("w-100");
        $(".third-hex-text").removeClass("w-100");
        $(".q4-stablity").removeClass("fs-4").addClass("fs-6");
        $(".hex-input").addClass("ps-2");
        $(".q-4").css("overflow-y","auto");
        $("#q5-answer2").parent().addClass("mt-2");
        $("#q6-answer2").parent().addClass("mt-2");
        $("#q6-answer3").parent().addClass("mt-2");
        $("#q7-answer2").parent().addClass("mt-2");
        $("#q7-answer3").parent().addClass("mt-2");
        $("#q8-answer2").parent().addClass("mt-2");
        $("#q8-answer3").parent().addClass("mt-2");
        $("#q10-answer2").parent().addClass("mt-2");
        $("#q10-answer3").parent().addClass("mt-2");
        $("#q11-answer2").parent().addClass("mt-2");
        $("#q11-answer3").parent().addClass("mt-2");
        $("#q11-answer4").parent().addClass("mt-2");
        $("#q12-answer2").parent().addClass("mt-2");
        $("#q12-answer3").parent().addClass("mt-2");
        $("#q12-answer4").parent().addClass("mt-2");
        $("#q12-answer5").parent().addClass("mt-2");
        $("#q13-answer2").parent().addClass("mt-2");
        $("#q13-answer3").parent().addClass("mt-2");
        $("#q13-answer4").parent().addClass("mt-2");
        $("#q13-answer5").parent().addClass("mt-2");
        $("#q13-answer6").parent().addClass("mt-2");
        $("#q14-answer2").parent().addClass("mt-2");
        $("#q14-answer3").parent().addClass("mt-2");
        $("#q14-answer4").parent().addClass("mt-2");
        $("#q14-answer5").parent().addClass("mt-2");
        $("#q14-answer6").parent().addClass("mt-2");
        $("#q15-answer2").parent().addClass("mt-2");
        $("#q15-answer3").parent().addClass("mt-2");
        $("#q16-answer2").parent().addClass("mt-2");
        $("#q16-answer3").parent().addClass("mt-2");
        $("#q16-answer4").parent().addClass("mt-2");
        $("#q16-answer5").parent().addClass("mt-2");
    }else if(windowWidth >= 375 && windowWidth < 425){
        $(".second-hex-text").removeClass("w-100");
        $(".third-hex-text").removeClass("w-100");
        $(".q4-stablity").removeClass("fs-4").addClass("fs-6");
        $(".q-4").css("overflow-y","auto");
        $("#q5-answer2").parent().addClass("mt-2");
        $("#q6-answer2").parent().addClass("mt-2");
        $("#q6-answer3").parent().addClass("mt-2");
        $("#q7-answer2").parent().addClass("mt-2");
        $("#q7-answer3").parent().addClass("mt-2");
        $("#q8-answer2").parent().addClass("mt-2");
        $("#q8-answer3").parent().addClass("mt-2");
        $("#q10-answer2").parent().addClass("mt-2");
        $("#q10-answer3").parent().addClass("mt-2");
        $("#q11-answer2").parent().addClass("mt-2");
        $("#q11-answer3").parent().addClass("mt-2");
        $("#q11-answer4").parent().addClass("mt-2");
        $("#q12-answer2").parent().addClass("mt-2");
        $("#q12-answer3").parent().addClass("mt-2");
        $("#q12-answer4").parent().addClass("mt-2");
        $("#q12-answer5").parent().addClass("mt-2");
        $("#q13-answer2").parent().addClass("mt-2");
        $("#q13-answer3").parent().addClass("mt-2");
        $("#q13-answer4").parent().addClass("mt-2");
        $("#q13-answer5").parent().addClass("mt-2");
        $("#q13-answer6").parent().addClass("mt-2");
        $("#q14-answer2").parent().addClass("mt-2");
        $("#q14-answer3").parent().addClass("mt-2");
        $("#q14-answer4").parent().addClass("mt-2");
        $("#q14-answer5").parent().addClass("mt-2");
        $("#q14-answer6").parent().addClass("mt-2");
        $("#q15-answer2").parent().addClass("mt-2");
        $("#q15-answer3").parent().addClass("mt-2");
        $("#q16-answer2").parent().addClass("mt-2");
        $("#q16-answer3").parent().addClass("mt-2");
        $("#q16-answer4").parent().addClass("mt-2");
        $("#q16-answer5").parent().addClass("mt-2");
    }else if(windowWidth >= 425 && windowWidth < 768){
        $(".second-hex-text").removeClass("w-100");
        $(".third-hex-text").removeClass("w-100");
        $(".q-4").css("overflow-y","auto");
        $("#q5-answer2").parent().addClass("mt-2");
        $("#q6-answer2").parent().addClass("mt-2");
        $("#q6-answer3").parent().addClass("mt-2");
        $("#q7-answer2").parent().addClass("mt-2");
        $("#q7-answer3").parent().addClass("mt-2");
        $("#q8-answer2").parent().addClass("mt-2");
        $("#q8-answer3").parent().addClass("mt-2");
        $("#q10-answer2").parent().addClass("mt-2");
        $("#q10-answer3").parent().addClass("mt-2");
        $("#q11-answer2").parent().addClass("mt-2");
        $("#q11-answer3").parent().addClass("mt-2");
        $("#q11-answer4").parent().addClass("mt-2");
        $("#q12-answer2").parent().addClass("mt-2");
        $("#q12-answer3").parent().addClass("mt-2");
        $("#q12-answer4").parent().addClass("mt-2");
        $("#q12-answer5").parent().addClass("mt-2");
        $("#q13-answer2").parent().addClass("mt-2");
        $("#q13-answer3").parent().addClass("mt-2");
        $("#q13-answer4").parent().addClass("mt-2");
        $("#q13-answer5").parent().addClass("mt-2");
        $("#q13-answer6").parent().addClass("mt-2");
        $("#q14-answer2").parent().addClass("mt-2");
        $("#q14-answer3").parent().addClass("mt-2");
        $("#q14-answer4").parent().addClass("mt-2");
        $("#q14-answer5").parent().addClass("mt-2");
        $("#q14-answer6").parent().addClass("mt-2");
        $("#q15-answer2").parent().addClass("mt-2");
        $("#q15-answer3").parent().addClass("mt-2");
        $("#q16-answer2").parent().addClass("mt-2");
        $("#q16-answer3").parent().addClass("mt-2");
        $("#q16-answer4").parent().addClass("mt-2");
        $("#q16-answer5").parent().addClass("mt-2");
    }else if(windowWidth >= 768 && windowWidth < 1024){
        $(".q-4").css("overflow-y","auto");
        $("#q5-answer2").parent().addClass("mt-2");
        $("#q6-answer2").parent().addClass("mt-2");
        $("#q6-answer3").parent().addClass("mt-2");
        $("#q7-answer2").parent().addClass("mt-2");
        $("#q7-answer3").parent().addClass("mt-2");
        $("#q8-answer2").parent().addClass("mt-2");
        $("#q8-answer3").parent().addClass("mt-2");
        $("#q10-answer2").parent().addClass("mt-2");
        $("#q10-answer3").parent().addClass("mt-2");
        $("#q11-answer2").parent().addClass("mt-2");
        $("#q11-answer3").parent().addClass("mt-2");
        $("#q11-answer4").parent().addClass("mt-2");
        $("#q12-answer2").parent().addClass("mt-2");
        $("#q12-answer3").parent().addClass("mt-2");
        $("#q12-answer4").parent().addClass("mt-2");
        $("#q12-answer5").parent().addClass("mt-2");
        $("#q13-answer2").parent().addClass("mt-2");
        $("#q13-answer3").parent().addClass("mt-2");
        $("#q13-answer4").parent().addClass("mt-2");
        $("#q13-answer5").parent().addClass("mt-2");
        $("#q13-answer6").parent().addClass("mt-2");
        $("#q14-answer2").parent().addClass("mt-2");
        $("#q14-answer3").parent().addClass("mt-2");
        $("#q14-answer4").parent().addClass("mt-2");
        $("#q14-answer5").parent().addClass("mt-2");
        $("#q14-answer6").parent().addClass("mt-2");
        $("#q15-answer2").parent().addClass("mt-2");
        $("#q15-answer3").parent().addClass("mt-2");
        $("#q16-answer2").parent().addClass("mt-2");
        $("#q16-answer3").parent().addClass("mt-2");
        $("#q16-answer4").parent().addClass("mt-2");
        $("#q16-answer5").parent().addClass("mt-2");
    }else if(windowWidth >= 1024 && windowWidth < 1440){
        $(".q-4").css("overflow-y","auto");
        $("#q12-answer4").parent().parent().addClass("mt-2");
        $("#q14-answer4").parent().parent().addClass("mt-2");
        $("#q13-answer4").parent().parent().addClass("mt-2");
        $("#q16-answer4").parent().parent().addClass("mt-2");
    }else if(windowWidth >= 1440 && windowWidth < 1920){
        $(".second-hex-text").removeClass("w-100");
        $(".third-hex-text").removeClass("w-100");
        $("#q12-answer4").parent().parent().addClass("mt-2");
        $("#q14-answer4").parent().parent().addClass("mt-2");
        $("#q13-answer4").parent().parent().addClass("mt-2");
        $("#q16-answer4").parent().parent().addClass("mt-2");
    }else if(windowWidth >= 1920 && windowWidth < 2560){
        $("#q12-answer4").parent().parent().addClass("mt-2");
        $("#q14-answer4").parent().parent().addClass("mt-2");
        $("#q13-answer4").parent().parent().addClass("mt-2");
        $("#q16-answer4").parent().parent().addClass("mt-2");
    }else if(windowWidth >= 2560){
        $("#q12-answer4").parent().parent().addClass("mt-2");
        $("#q14-answer4").parent().parent().addClass("mt-2");
        $("#q13-answer4").parent().parent().addClass("mt-2");
        $("#q16-answer4").parent().parent().addClass("mt-2");
    }
    if(windowWidth < 425){
        setTimeout(() => {
            $("#PRTEC06").html("2D");
            $("#PRTEC07").html("3D");
            $("#PRTEC09").html("영상");
            $("#PRTEC10").html("문서");
        }, 200);
    }
    if(windowWidth >= 576){
        setTimeout(() => {
            $(".modal-btn-col").children("button").removeClass("w-100").addClass("w-25");
            $(".modal-btn-col").children("h5").removeClass("w-100 pt-3").addClass("w-25");
            var modalBtnWidth = $(".modal-btn").width();
            var modalBtnPaddingLeft = parseFloat($(".modal-btn").css("padding-left"));
            var modalBtnPaddingRight = parseFloat($(".modal-btn").css("padding-right"));
            $(".modal-btn").height((modalBtnWidth + modalBtnPaddingLeft + modalBtnPaddingRight)/2);
        }, 200);
    }else if(windowWidth < 576){
        $(".modal-btn-col").children("button").removeClass("w-25").addClass("w-100");
        $(".modal-btn-col").children("h5").removeClass("w-75").addClass("w-100 pt-3");
    };
        
    if(windowWidth < 768){
        $("#select-date-modal-start-btn").addClass("mt-2");
        $(".side-empty").css("width","1%");
        $(".main-box").removeClass("container").css("width","98%");
        $("#sidebarToggle").attr("onclick","javascript:resizeEsBtn()");
    }else if(windowWidth >= 768){
        $(".side-empty").css("width","10%");
        $(".main-box").css("width","80%");
        $("#sidebarToggle").removeAttr("onclick","javascript:resizeEsBtn()");
        $(".modal-btn-col.new-btn").addClass("pb-2 border-bottom");
    }
    

    if(windowWidth < 1400){
        $(".question-col-3").addClass("mt-4");
    };
    if(windowWidth <= 1530  && windowWidth >= 1400){
        $(".question-col-3").children().children("p").css("font-size","14px");
    }else {
        $(".question-col-3").children().children("p").css("font-size","16px");
    }

    $(window).on("resize",function(){
        var windowWidth = window.outerWidth;
    
        if(windowWidth >= 576){
            setTimeout(() => {
                $(".modal-btn-col").children("button").removeClass("w-100").addClass("w-25");
                $(".modal-btn-col").children("h5").removeClass("w-100 pt-3").addClass("w-75");
                var modalBtnWidth = $(".modal-btn").width();
                var modalBtnPaddingLeft = parseFloat($(".modal-btn").css("padding-left"));
                var modalBtnPaddingRight = parseFloat($(".modal-btn").css("padding-right"));
                $(".modal-btn").height((modalBtnWidth + modalBtnPaddingLeft + modalBtnPaddingRight)/2);
            }, 200);
        }else if(windowWidth < 576){
            $(".modal-btn-col").children("button").removeClass("w-25").addClass("w-100");
            $(".modal-btn-col").children("h5").removeClass("w-75").addClass("w-100 pt-3");
        };

        if(windowWidth < 768){
            $("#select-date-modal-start-btn").addClass("mt-2");
            $(".side-empty").css("width","1%");
            $(".main-box").removeClass("container").css("width","98%");
            resizeEsBtn();
            $("#sidebarToggle").attr("onclick","javascript:resizeEsBtn()");
        }else if(windowWidth >= 768){
            $("#select-date-modal-start-btn").removeClass("mt-2");
            $(".side-empty").css("width","10%");
            $(".main-box").css("width","80%");
            $("#es-btn").css("display","block");
            $("#sidebarToggle").removeAttr("onclick","javascript:resizeEsBtn()");
            $(".modal-btn-col.new-btn").addClass("pb-2 border-bottom");
        }

        if(windowWidth < 1400){
            $(".question-col-3").addClass("mt-4");
        }else {
            $(".question-col-3").removeClass("mt-4");
        }

        if(windowWidth <= 1530 && windowWidth >= 1400){
            $(".question-col-3").children().children("p").css("font-size","14px");
        }else {
            $(".question-col-3").children().children("p").css("font-size","16px");
        }
        if(windowWidth >= 320 && windowWidth < 375){
            $(".second-hex-text").removeClass("w-100");
            $(".third-hex-text").removeClass("w-100");
            $(".q4-stablity").removeClass("fs-4").addClass("fs-6");
            $(".hex-input").addClass("ps-2");
            $(".q-4").css("overflow-y","auto");
            $("#q5-answer2").parent().addClass("mt-2");
            $("#q6-answer2").parent().addClass("mt-2");
            $("#q6-answer3").parent().addClass("mt-2");
            $("#q7-answer2").parent().addClass("mt-2");
            $("#q7-answer3").parent().addClass("mt-2");
            $("#q8-answer2").parent().addClass("mt-2");
            $("#q8-answer3").parent().addClass("mt-2");
            $("#q10-answer2").parent().addClass("mt-2");
            $("#q10-answer3").parent().addClass("mt-2");
            $("#q11-answer2").parent().addClass("mt-2");
            $("#q11-answer3").parent().addClass("mt-2");
            $("#q11-answer4").parent().addClass("mt-2");
            $("#q12-answer2").parent().addClass("mt-2");
            $("#q12-answer3").parent().addClass("mt-2");
            $("#q12-answer4").parent().addClass("mt-2");
            $("#q12-answer5").parent().addClass("mt-2");
            $("#q13-answer2").parent().addClass("mt-2");
            $("#q13-answer3").parent().addClass("mt-2");
            $("#q13-answer4").parent().addClass("mt-2");
            $("#q13-answer5").parent().addClass("mt-2");
            $("#q13-answer6").parent().addClass("mt-2");
            $("#q14-answer2").parent().addClass("mt-2");
            $("#q14-answer3").parent().addClass("mt-2");
            $("#q14-answer4").parent().addClass("mt-2");
            $("#q14-answer5").parent().addClass("mt-2");
            $("#q14-answer6").parent().addClass("mt-2");
            $("#q15-answer2").parent().addClass("mt-2");
            $("#q15-answer3").parent().addClass("mt-2");
            $("#q16-answer2").parent().addClass("mt-2");
            $("#q16-answer3").parent().addClass("mt-2");
            $("#q16-answer4").parent().addClass("mt-2");
            $("#q16-answer5").parent().addClass("mt-2");
        }else if(windowWidth >= 375 && windowWidth < 425){
            $(".second-hex-text").removeClass("w-100");
            $(".third-hex-text").removeClass("w-100");
            $(".q4-stablity").removeClass("fs-4").addClass("fs-6");
            $(".hex-input").removeClass("ps-2");
            $(".q-4").css("overflow-y","auto");
            $("#q5-answer2").parent().addClass("mt-2");
            $("#q6-answer2").parent().addClass("mt-2");
            $("#q6-answer3").parent().addClass("mt-2");
            $("#q7-answer2").parent().addClass("mt-2");
            $("#q7-answer3").parent().addClass("mt-2");
            $("#q8-answer2").parent().addClass("mt-2");
            $("#q8-answer3").parent().addClass("mt-2");
            $("#q10-answer2").parent().addClass("mt-2");
            $("#q10-answer3").parent().addClass("mt-2");
            $("#q11-answer2").parent().addClass("mt-2");
            $("#q11-answer3").parent().addClass("mt-2");
            $("#q11-answer4").parent().addClass("mt-2");
            $("#q12-answer2").parent().addClass("mt-2");
            $("#q12-answer3").parent().addClass("mt-2");
            $("#q12-answer4").parent().addClass("mt-2");
            $("#q12-answer5").parent().addClass("mt-2");
            $("#q13-answer2").parent().addClass("mt-2");
            $("#q13-answer3").parent().addClass("mt-2");
            $("#q13-answer4").parent().addClass("mt-2");
            $("#q13-answer5").parent().addClass("mt-2");
            $("#q13-answer6").parent().addClass("mt-2");
            $("#q14-answer2").parent().addClass("mt-2");
            $("#q14-answer3").parent().addClass("mt-2");
            $("#q14-answer4").parent().addClass("mt-2");
            $("#q14-answer5").parent().addClass("mt-2");
            $("#q14-answer6").parent().addClass("mt-2");
            $("#q15-answer2").parent().addClass("mt-2");
            $("#q15-answer3").parent().addClass("mt-2");
            $("#q16-answer2").parent().addClass("mt-2");
            $("#q16-answer3").parent().addClass("mt-2");
            $("#q16-answer4").parent().addClass("mt-2");
            $("#q16-answer5").parent().addClass("mt-2");
        }else if(windowWidth >= 425 && windowWidth < 768){
            $(".second-hex-text").removeClass("w-100");
            $(".third-hex-text").removeClass("w-100");
            $(".q4-stablity").addClass("fs-4").removeClass("fs-6");
            $(".hex-input").removeClass("ps-2");
            $(".q-4").css("overflow-y","auto");
            $("#q5-answer2").parent().addClass("mt-2");
            $("#q6-answer2").parent().addClass("mt-2");
            $("#q6-answer3").parent().addClass("mt-2");
            $("#q7-answer2").parent().addClass("mt-2");
            $("#q7-answer3").parent().addClass("mt-2");
            $("#q8-answer2").parent().addClass("mt-2");
            $("#q8-answer3").parent().addClass("mt-2");
            $("#q10-answer2").parent().addClass("mt-2");
            $("#q10-answer3").parent().addClass("mt-2");
            $("#q11-answer2").parent().addClass("mt-2");
            $("#q11-answer3").parent().addClass("mt-2");
            $("#q11-answer4").parent().addClass("mt-2");
            $("#q12-answer2").parent().addClass("mt-2");
            $("#q12-answer3").parent().addClass("mt-2");
            $("#q12-answer4").parent().addClass("mt-2");
            $("#q12-answer5").parent().addClass("mt-2");
            $("#q13-answer2").parent().addClass("mt-2");
            $("#q13-answer3").parent().addClass("mt-2");
            $("#q13-answer4").parent().addClass("mt-2");
            $("#q13-answer5").parent().addClass("mt-2");
            $("#q13-answer6").parent().addClass("mt-2");
            $("#q14-answer2").parent().addClass("mt-2");
            $("#q14-answer3").parent().addClass("mt-2");
            $("#q14-answer4").parent().addClass("mt-2");
            $("#q14-answer5").parent().addClass("mt-2");
            $("#q14-answer6").parent().addClass("mt-2");
            $("#q15-answer2").parent().addClass("mt-2");
            $("#q15-answer3").parent().addClass("mt-2");
            $("#q16-answer2").parent().addClass("mt-2");
            $("#q16-answer3").parent().addClass("mt-2");
            $("#q16-answer4").parent().addClass("mt-2");
            $("#q16-answer5").parent().addClass("mt-2");
        }else if(windowWidth >= 768 && windowWidth < 1024){
            $(".second-hex-text").addClass("w-100");
            $(".third-hex-text").addClass("w-100");
            $(".q4-stablity").addClass("fs-4").removeClass("fs-6");
            $(".hex-input").removeClass("ps-2");
            $(".q-4").css("overflow-y","auto");
            $("#q5-answer2").parent().addClass("mt-2");
            $("#q6-answer2").parent().addClass("mt-2");
            $("#q6-answer3").parent().addClass("mt-2");
            $("#q7-answer2").parent().addClass("mt-2");
            $("#q7-answer3").parent().addClass("mt-2");
            $("#q8-answer2").parent().addClass("mt-2");
            $("#q8-answer3").parent().addClass("mt-2");
            $("#q10-answer2").parent().addClass("mt-2");
            $("#q10-answer3").parent().addClass("mt-2");
            $("#q11-answer2").parent().addClass("mt-2");
            $("#q11-answer3").parent().addClass("mt-2");
            $("#q11-answer4").parent().addClass("mt-2");
            $("#q12-answer2").parent().addClass("mt-2");
            $("#q12-answer3").parent().addClass("mt-2");
            $("#q12-answer4").parent().addClass("mt-2");
            $("#q12-answer5").parent().addClass("mt-2");
            $("#q13-answer2").parent().addClass("mt-2");
            $("#q13-answer3").parent().addClass("mt-2");
            $("#q13-answer4").parent().addClass("mt-2");
            $("#q13-answer5").parent().addClass("mt-2");
            $("#q13-answer6").parent().addClass("mt-2");
            $("#q14-answer2").parent().addClass("mt-2");
            $("#q14-answer3").parent().addClass("mt-2");
            $("#q14-answer4").parent().addClass("mt-2");
            $("#q14-answer5").parent().addClass("mt-2");
            $("#q14-answer6").parent().addClass("mt-2");
            $("#q15-answer2").parent().addClass("mt-2");
            $("#q15-answer3").parent().addClass("mt-2");
            $("#q16-answer2").parent().addClass("mt-2");
            $("#q16-answer3").parent().addClass("mt-2");
            $("#q16-answer4").parent().addClass("mt-2");
            $("#q16-answer5").parent().addClass("mt-2");
        }else if(windowWidth >= 1024 && windowWidth < 1440){
            $(".second-hex-text").addClass("w-100");
            $(".third-hex-text").addClass("w-100");
            $(".q4-stablity").addClass("fs-4").removeClass("fs-6");
            $(".hex-input").removeClass("ps-2");
            $(".q-4").css("overflow-y","auto");
            $("#q12-answer4").parent().parent().addClass("mt-2");
            $("#q14-answer4").parent().parent().addClass("mt-2");
            $("#q13-answer4").parent().parent().addClass("mt-2");
            $("#q16-answer4").parent().parent().addClass("mt-2");
            $("#q5-answer2").parent().removeClass("mt-2");
            $("#q6-answer2").parent().removeClass("mt-2");
            $("#q6-answer3").parent().removeClass("mt-2");
            $("#q7-answer2").parent().removeClass("mt-2");
            $("#q7-answer3").parent().removeClass("mt-2");
            $("#q8-answer2").parent().removeClass("mt-2");
            $("#q8-answer3").parent().removeClass("mt-2");
            $("#q10-answer2").parent().removeClass("mt-2");
            $("#q10-answer3").parent().removeClass("mt-2");
            $("#q11-answer2").parent().removeClass("mt-2");
            $("#q11-answer3").parent().removeClass("mt-2");
            $("#q11-answer4").parent().removeClass("mt-2");
            $("#q12-answer2").parent().removeClass("mt-2");
            $("#q12-answer3").parent().removeClass("mt-2");
            $("#q12-answer4").parent().removeClass("mt-2");
            $("#q12-answer5").parent().removeClass("mt-2");
            $("#q13-answer2").parent().removeClass("mt-2");
            $("#q13-answer3").parent().removeClass("mt-2");
            $("#q13-answer4").parent().removeClass("mt-2");
            $("#q13-answer5").parent().removeClass("mt-2");
            $("#q13-answer6").parent().removeClass("mt-2");
            $("#q14-answer2").parent().removeClass("mt-2");
            $("#q14-answer3").parent().removeClass("mt-2");
            $("#q14-answer4").parent().removeClass("mt-2");
            $("#q14-answer5").parent().removeClass("mt-2");
            $("#q14-answer6").parent().removeClass("mt-2");
            $("#q15-answer2").parent().removeClass("mt-2");
            $("#q15-answer3").parent().removeClass("mt-2");
            $("#q16-answer2").parent().removeClass("mt-2");
            $("#q16-answer3").parent().removeClass("mt-2");
            $("#q16-answer4").parent().removeClass("mt-2");
            $("#q16-answer5").parent().removeClass("mt-2");
        }else if(windowWidth >= 1440 && windowWidth < 1920){
            $(".second-hex-text").removeClass("w-100");
            $(".third-hex-text").removeClass("w-100");
            $(".q4-stablity").addClass("fs-4").removeClass("fs-6");
            $(".hex-input").removeClass("ps-2");
            $(".q-4").css("overflow-y","clip");
            $("#q12-answer4").parent().parent().addClass("mt-2");
            $("#q14-answer4").parent().parent().addClass("mt-2");
            $("#q13-answer4").parent().parent().addClass("mt-2");
            $("#q16-answer4").parent().parent().addClass("mt-2");
            $("#q5-answer2").parent().removeClass("mt-2");
            $("#q6-answer2").parent().removeClass("mt-2");
            $("#q6-answer3").parent().removeClass("mt-2");
            $("#q7-answer2").parent().removeClass("mt-2");
            $("#q7-answer3").parent().removeClass("mt-2");
            $("#q8-answer2").parent().removeClass("mt-2");
            $("#q8-answer3").parent().removeClass("mt-2");
            $("#q10-answer2").parent().removeClass("mt-2");
            $("#q10-answer3").parent().removeClass("mt-2");
            $("#q11-answer2").parent().removeClass("mt-2");
            $("#q11-answer3").parent().removeClass("mt-2");
            $("#q11-answer4").parent().removeClass("mt-2");
            $("#q12-answer2").parent().removeClass("mt-2");
            $("#q12-answer3").parent().removeClass("mt-2");
            $("#q12-answer4").parent().removeClass("mt-2");
            $("#q12-answer5").parent().removeClass("mt-2");
            $("#q13-answer2").parent().removeClass("mt-2");
            $("#q13-answer3").parent().removeClass("mt-2");
            $("#q13-answer4").parent().removeClass("mt-2");
            $("#q13-answer5").parent().removeClass("mt-2");
            $("#q13-answer6").parent().removeClass("mt-2");
            $("#q14-answer2").parent().removeClass("mt-2");
            $("#q14-answer3").parent().removeClass("mt-2");
            $("#q14-answer4").parent().removeClass("mt-2");
            $("#q14-answer5").parent().removeClass("mt-2");
            $("#q14-answer6").parent().removeClass("mt-2");
            $("#q15-answer2").parent().removeClass("mt-2");
            $("#q15-answer3").parent().removeClass("mt-2");
            $("#q16-answer2").parent().removeClass("mt-2");
            $("#q16-answer3").parent().removeClass("mt-2");
            $("#q16-answer4").parent().removeClass("mt-2");
            $("#q16-answer5").parent().removeClass("mt-2");
        }else if(windowWidth >= 1920 && windowWidth < 2560){
            $(".second-hex-text").addClass("w-100");
            $(".third-hex-text").addClass("w-100");
            $(".q4-stablity").addClass("fs-4").removeClass("fs-6");
            $(".hex-input").removeClass("ps-2");
            $(".q-4").css("overflow-y","clip");
            $("#q12-answer4").parent().parent().addClass("mt-2");
            $("#q14-answer4").parent().parent().addClass("mt-2");
            $("#q13-answer4").parent().parent().addClass("mt-2");
            $("#q16-answer4").parent().parent().addClass("mt-2");
            $("#q5-answer2").parent().removeClass("mt-2");
            $("#q6-answer2").parent().removeClass("mt-2");
            $("#q6-answer3").parent().removeClass("mt-2");
            $("#q7-answer2").parent().removeClass("mt-2");
            $("#q7-answer3").parent().removeClass("mt-2");
            $("#q8-answer2").parent().removeClass("mt-2");
            $("#q8-answer3").parent().removeClass("mt-2");
            $("#q10-answer2").parent().removeClass("mt-2");
            $("#q10-answer3").parent().removeClass("mt-2");
            $("#q11-answer2").parent().removeClass("mt-2");
            $("#q11-answer3").parent().removeClass("mt-2");
            $("#q11-answer4").parent().removeClass("mt-2");
            $("#q12-answer2").parent().removeClass("mt-2");
            $("#q12-answer3").parent().removeClass("mt-2");
            $("#q12-answer4").parent().removeClass("mt-2");
            $("#q12-answer5").parent().removeClass("mt-2");
            $("#q13-answer2").parent().removeClass("mt-2");
            $("#q13-answer3").parent().removeClass("mt-2");
            $("#q13-answer4").parent().removeClass("mt-2");
            $("#q13-answer5").parent().removeClass("mt-2");
            $("#q13-answer6").parent().removeClass("mt-2");
            $("#q14-answer2").parent().removeClass("mt-2");
            $("#q14-answer3").parent().removeClass("mt-2");
            $("#q14-answer4").parent().removeClass("mt-2");
            $("#q14-answer5").parent().removeClass("mt-2");
            $("#q14-answer6").parent().removeClass("mt-2");
            $("#q15-answer2").parent().removeClass("mt-2");
            $("#q15-answer3").parent().removeClass("mt-2");
            $("#q16-answer2").parent().removeClass("mt-2");
            $("#q16-answer3").parent().removeClass("mt-2");
            $("#q16-answer4").parent().removeClass("mt-2");
            $("#q16-answer5").parent().removeClass("mt-2");
        }else if(windowWidth >= 2560){
            $(".second-hex-text").addClass("w-100");
            $(".third-hex-text").addClass("w-100");
            $(".q4-stablity").addClass("fs-4").removeClass("fs-6");
            $(".hex-input").removeClass("ps-2");
            $(".q-4").css("overflow-y","clip");
            $("#q12-answer4").parent().parent().addClass("mt-2");
            $("#q14-answer4").parent().parent().addClass("mt-2");
            $("#q13-answer4").parent().parent().addClass("mt-2");
            $("#q16-answer4").parent().parent().addClass("mt-2");
            $("#q5-answer2").parent().removeClass("mt-2");
            $("#q6-answer2").parent().removeClass("mt-2");
            $("#q6-answer3").parent().removeClass("mt-2");
            $("#q7-answer2").parent().removeClass("mt-2");
            $("#q7-answer3").parent().removeClass("mt-2");
            $("#q8-answer2").parent().removeClass("mt-2");
            $("#q8-answer3").parent().removeClass("mt-2");
            $("#q10-answer2").parent().removeClass("mt-2");
            $("#q10-answer3").parent().removeClass("mt-2");
            $("#q11-answer2").parent().removeClass("mt-2");
            $("#q11-answer3").parent().removeClass("mt-2");
            $("#q11-answer4").parent().removeClass("mt-2");
            $("#q12-answer2").parent().removeClass("mt-2");
            $("#q12-answer3").parent().removeClass("mt-2");
            $("#q12-answer4").parent().removeClass("mt-2");
            $("#q12-answer5").parent().removeClass("mt-2");
            $("#q13-answer2").parent().removeClass("mt-2");
            $("#q13-answer3").parent().removeClass("mt-2");
            $("#q13-answer4").parent().removeClass("mt-2");
            $("#q13-answer5").parent().removeClass("mt-2");
            $("#q13-answer6").parent().removeClass("mt-2");
            $("#q14-answer2").parent().removeClass("mt-2");
            $("#q14-answer3").parent().removeClass("mt-2");
            $("#q14-answer4").parent().removeClass("mt-2");
            $("#q14-answer5").parent().removeClass("mt-2");
            $("#q14-answer6").parent().removeClass("mt-2");
            $("#q15-answer2").parent().removeClass("mt-2");
            $("#q15-answer3").parent().removeClass("mt-2");
            $("#q16-answer2").parent().removeClass("mt-2");
            $("#q16-answer3").parent().removeClass("mt-2");
            $("#q16-answer4").parent().removeClass("mt-2");
            $("#q16-answer5").parent().removeClass("mt-2");
        }
    });
})